2020-04-24 16:50:44,185 | INFO | BDC7-L-9361NF2 |         [__init__ <module>] | Executing Initial User data setup
2020-04-24 16:50:44,248 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: devnetopsV2.role index: name_1 dup key: { : "admin" })
2020-04-24 16:50:44,248 | ERROR | BDC7-L-9361NF2 |         [datasetup <module>] | Role-"admin" Creation failed
2020-04-24 16:50:50,282 | INFO | BDC7-L-9361NF2 |         [__init__ <module>] | Executing Initial User data setup
2020-04-24 16:50:50,308 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: devnetopsV2.role index: name_1 dup key: { : "admin" })
2020-04-24 16:50:50,309 | ERROR | BDC7-L-9361NF2 |         [datasetup <module>] | Role-"admin" Creation failed
2020-04-27 13:09:25,012 | INFO | BDC7-L-9361NF2 |         [__init__ <module>] | Executing Initial User data setup
2020-04-27 13:09:25,078 | INFO | BDC7-L-9361NF2 |         [db createRole] | Role "admin"" created
2020-04-27 13:09:25,078 | INFO | BDC7-L-9361NF2 |         [datasetup <module>] | Role-"admin" Created
2020-04-27 13:09:25,099 | INFO | BDC7-L-9361NF2 |         [datasetup <module>] | User - "admin@acc.com" created
2020-04-27 13:15:08,055 | INFO | BDC7-L-9361NF2 |         [__init__ <module>] | Executing Initial User data setup
2020-04-27 13:15:08,138 | INFO | BDC7-L-9361NF2 |         [db createRole] | Role "admin"" created
2020-04-27 13:15:08,138 | INFO | BDC7-L-9361NF2 |         [datasetup <module>] | Role-"admin" Created
2020-04-27 13:15:08,173 | INFO | BDC7-L-9361NF2 |         [datasetup <module>] | User - "admin@acc.com" created
2020-04-27 13:15:11,602 | INFO | BDC7-L-9361NF2 |         [__init__ <module>] | Executing Initial User data setup
2020-04-27 13:15:11,623 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: devnetopsV2.role index: name_1 dup key: { : "admin" })
2020-04-27 13:15:11,623 | ERROR | BDC7-L-9361NF2 |         [datasetup <module>] | Role-"admin" Creation failed
2020-04-27 13:19:45,123 | INFO | BDC7-L-9361NF2 |         [__init__ <module>] | Executing Initial User data setup
2020-04-27 13:19:45,163 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: devnetopsV2.role index: name_1 dup key: { : "admin" })
2020-04-27 13:19:45,164 | ERROR | BDC7-L-9361NF2 |         [datasetup <module>] | Role-"admin" Creation failed
2020-04-27 13:19:48,774 | INFO | BDC7-L-9361NF2 |         [__init__ <module>] | Executing Initial User data setup
2020-04-27 13:19:48,791 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: devnetopsV2.role index: name_1 dup key: { : "admin" })
2020-04-27 13:19:48,791 | ERROR | BDC7-L-9361NF2 |         [datasetup <module>] | Role-"admin" Creation failed
2020-04-27 13:22:42,659 | INFO | BDC7-L-9361NF2 |         [__init__ <module>] | Executing Initial User data setup
2020-04-27 13:22:42,678 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: devnetopsV2.role index: name_1 dup key: { : "admin" })
2020-04-27 13:22:42,678 | ERROR | BDC7-L-9361NF2 |         [datasetup <module>] | Role-"admin" Creation failed
2020-04-27 14:05:04,674 | INFO | BDC7-L-9361NF2 |         [__init__ <module>] | Executing Initial User data setup
2020-04-27 14:05:04,705 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: devnetopsV2.role index: name_1 dup key: { : "admin" })
2020-04-27 14:05:04,707 | ERROR | BDC7-L-9361NF2 |         [datasetup <module>] | Role-"admin" Creation failed
2020-04-27 14:05:09,423 | INFO | BDC7-L-9361NF2 |         [__init__ <module>] | Executing Initial User data setup
2020-04-27 14:05:09,440 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: devnetopsV2.role index: name_1 dup key: { : "admin" })
2020-04-27 14:05:09,440 | ERROR | BDC7-L-9361NF2 |         [datasetup <module>] | Role-"admin" Creation failed
2020-04-27 14:05:14,613 | ERROR | BDC7-L-9361NF2 |         [db getRoles] | 'Services' object has no attribute 'name'
2020-04-27 14:07:33,813 | INFO | BDC7-L-9361NF2 |         [__init__ <module>] | Executing Initial User data setup
2020-04-27 14:07:33,839 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: devnetopsV2.role index: name_1 dup key: { : "admin" })
2020-04-27 14:07:33,841 | ERROR | BDC7-L-9361NF2 |         [datasetup <module>] | Role-"admin" Creation failed
2020-04-27 14:16:54,352 | INFO | BDC7-L-9361NF2 |         [__init__ <module>] | Executing Initial User data setup
2020-04-27 14:16:54,384 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: devnetopsV2.role index: name_1 dup key: { : "admin" })
2020-04-27 14:16:54,385 | ERROR | BDC7-L-9361NF2 |         [datasetup <module>] | Role-"admin" Creation failed
2020-04-27 14:21:49,942 | INFO | BDC7-L-9361NF2 |         [__init__ <module>] | Executing Initial User data setup
2020-04-27 14:21:49,965 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: devnetopsV2.role index: name_1 dup key: { : "admin" })
2020-04-27 14:21:49,966 | ERROR | BDC7-L-9361NF2 |         [datasetup <module>] | Role-"admin" Creation failed
2020-04-27 14:21:56,104 | INFO | BDC7-L-9361NF2 |         [__init__ <module>] | Executing Initial User data setup
2020-04-27 14:21:56,130 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: devnetopsV2.role index: name_1 dup key: { : "admin" })
2020-04-27 14:21:56,132 | ERROR | BDC7-L-9361NF2 |         [datasetup <module>] | Role-"admin" Creation failed
2020-04-27 14:21:59,107 | ERROR | BDC7-L-9361NF2 |         [db userRoles] | name
2020-04-27 14:22:40,663 | INFO | BDC7-L-9361NF2 |         [__init__ <module>] | Executing Initial User data setup
2020-04-27 14:22:40,701 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: devnetopsV2.role index: name_1 dup key: { : "admin" })
2020-04-27 14:22:40,701 | ERROR | BDC7-L-9361NF2 |         [datasetup <module>] | Role-"admin" Creation failed
2020-04-27 14:22:41,355 | ERROR | BDC7-L-9361NF2 |         [db userRoles] | name
2020-04-27 14:24:47,590 | INFO | BDC7-L-9361NF2 |         [__init__ <module>] | Executing Initial User data setup
2020-04-27 14:24:47,629 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: devnetopsV2.role index: name_1 dup key: { : "admin" })
2020-04-27 14:24:47,630 | ERROR | BDC7-L-9361NF2 |         [datasetup <module>] | Role-"admin" Creation failed
2020-04-27 14:24:52,132 | ERROR | BDC7-L-9361NF2 |         [db userRoles] | name
2020-04-27 14:26:52,943 | INFO | BDC7-L-9361NF2 |         [__init__ <module>] | Executing Initial User data setup
2020-04-27 14:26:52,980 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: devnetopsV2.role index: name_1 dup key: { : "admin" })
2020-04-27 14:26:52,980 | ERROR | BDC7-L-9361NF2 |         [datasetup <module>] | Role-"admin" Creation failed
2020-04-27 14:27:28,303 | INFO | BDC7-L-9361NF2 |         [__init__ <module>] | Executing Initial User data setup
2020-04-27 14:27:28,324 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: devnetopsV2.role index: name_1 dup key: { : "admin" })
2020-04-27 14:27:28,325 | ERROR | BDC7-L-9361NF2 |         [datasetup <module>] | Role-"admin" Creation failed
2020-04-27 14:27:42,458 | INFO | BDC7-L-9361NF2 |         [__init__ <module>] | Executing Initial User data setup
2020-04-27 14:27:42,524 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: devnetopsV2.role index: name_1 dup key: { : "admin" })
2020-04-27 14:27:42,525 | ERROR | BDC7-L-9361NF2 |         [datasetup <module>] | Role-"admin" Creation failed
2020-04-27 14:27:53,641 | ERROR | BDC7-L-9361NF2 |         [db userRoles] | name
2020-04-27 14:30:07,150 | INFO | BDC7-L-9361NF2 |         [__init__ <module>] | Executing Initial User data setup
2020-04-27 14:30:07,207 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: devnetopsV2.role index: name_1 dup key: { : "admin" })
2020-04-27 14:30:07,207 | ERROR | BDC7-L-9361NF2 |         [datasetup <module>] | Role-"admin" Creation failed
2020-04-27 14:30:57,439 | INFO | BDC7-L-9361NF2 |         [__init__ <module>] | Executing Initial User data setup
2020-04-27 14:30:57,485 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: devnetopsV2.role index: name_1 dup key: { : "admin" })
2020-04-27 14:30:57,486 | ERROR | BDC7-L-9361NF2 |         [datasetup <module>] | Role-"admin" Creation failed
2020-04-27 14:32:16,810 | INFO | BDC7-L-9361NF2 |         [__init__ <module>] | Executing Initial User data setup
2020-04-27 14:32:16,839 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: devnetopsV2.role index: name_1 dup key: { : "admin" })
2020-04-27 14:32:16,842 | ERROR | BDC7-L-9361NF2 |         [datasetup <module>] | Role-"admin" Creation failed
2020-04-27 14:32:20,599 | ERROR | BDC7-L-9361NF2 |         [db userRoles] | name
2020-04-27 14:36:46,388 | INFO | BDC7-L-9361NF2 |         [__init__ <module>] | Executing Initial User data setup
2020-04-27 14:36:46,496 | INFO | BDC7-L-9361NF2 |         [db createRole] | Role "admin"" created
2020-04-27 14:36:46,497 | INFO | BDC7-L-9361NF2 |         [datasetup <module>] | Role-"admin" Created
2020-04-27 14:36:46,610 | INFO | BDC7-L-9361NF2 |         [datasetup <module>] | User - "admin@acc.com" created
2020-04-27 14:36:51,230 | INFO | BDC7-L-9361NF2 |         [__init__ <module>] | Executing Initial User data setup
2020-04-27 14:36:51,277 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: devnetopsV2.role index: name_1 dup key: { : "admin" })
2020-04-27 14:36:51,278 | ERROR | BDC7-L-9361NF2 |         [datasetup <module>] | Role-"admin" Creation failed
2020-04-27 14:49:36,086 | INFO | BDC7-L-9361NF2 |         [db createRole] | Role "admin"" created
2020-04-27 16:44:32,623 | INFO | BDC7-L-9361NF2 |         [db createRole] | Role "admin"" created
2020-04-27 17:56:16,554 | INFO | BDC7-L-9361NF2 |         [db createRole] | Role "admin"" created
2020-04-27 17:56:55,222 | DEBUG | BDC7-L-9361NF2 |         [db createUser] | Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\Desktop\Devnetops\devnetops-feature_sprint1\UserMgmt\src\db\db.py", line 57, in createUser
    usr = User(user, passw, roles)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\base\document.py", line 78, in __init__
    raise TypeError(
TypeError: Instantiating a document with positional arguments is not supported. Please use `field_name=value` keyword arguments.

2020-04-27 17:56:55,223 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Instantiating a document with positional arguments is not supported. Please use `field_name=value` keyword arguments.
2020-04-27 17:59:58,729 | DEBUG | BDC7-L-9361NF2 |         [db createUser] | Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\Desktop\Devnetops\devnetops-feature_sprint1\UserMgmt\src\db\db.py", line 57, in createUser
    usr = User(user, passw)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\base\document.py", line 78, in __init__
    raise TypeError(
TypeError: Instantiating a document with positional arguments is not supported. Please use `field_name=value` keyword arguments.

2020-04-27 17:59:58,729 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Instantiating a document with positional arguments is not supported. Please use `field_name=value` keyword arguments.
2020-04-27 18:16:10,458 | INFO | BDC7-L-9361NF2 |         [db createRole] | Role "admin"" created
2020-04-27 22:31:32,529 | INFO | BDC7-L-9361NF2 |         [db createSvc] | Service 'svc1' has been created
2020-04-27 22:31:32,530 | INFO | BDC7-L-9361NF2 |         [db createSvc] | Service 'svc2' has been created
2020-04-27 22:31:32,631 | INFO | BDC7-L-9361NF2 |         [db createRole] | Role 'admin' has been created
2020-04-27 22:31:33,001 | INFO | BDC7-L-9361NF2 |         [db createUser] | User 'admin@acc.com' created with roles 'admin'
2020-04-27 22:31:33,003 | ERROR | BDC7-L-9361NF2 |         [db authenticateUser] | Failed to verify user 'admin@acc.com'
2020-04-27 22:31:33,005 | DEBUG | BDC7-L-9361NF2 |         [db authenticateUser] | Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\Desktop\Devnetops\devnetops-feature_sprint1\UserMgmt\src\db\db.py", line 257, in authenticateUser
    return checkpw(passw.encode('utf-8'), usr.password)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\bcrypt\__init__.py", line 100, in checkpw
    raise TypeError("Unicode-objects must be encoded before checking")
TypeError: Unicode-objects must be encoded before checking

2020-04-27 22:31:33,006 | ERROR | BDC7-L-9361NF2 |         [db authenticateUser] | Unicode-objects must be encoded before checking
2020-04-27 22:35:31,328 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 22:35:31,338 | DEBUG | BDC7-L-9361NF2 |         [db createSvc] | Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 412, in save
    object_id = self._save_create(doc, force_insert, write_concern)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 477, in _save_create
    object_id = wc_collection.insert_one(doc).inserted_id
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 695, in insert_one
    self._insert(document,
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 610, in _insert
    return self._insert_one(
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 599, in _insert_one
    self.__database.client._retryable_write(
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\mongo_client.py", line 1491, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\mongo_client.py", line 1384, in _retry_with_session
    return func(session, sock_info, retryable)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 597, in _insert_command
    _check_write_command_response(result)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\helpers.py", line 221, in _check_write_command_response
    _raise_last_write_error(write_errors)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\helpers.py", line 202, in _raise_last_write_error
    raise DuplicateKeyError(error.get("errmsg"), 11000, error)
pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\Desktop\Devnetops\devnetops-feature_sprint1\UserMgmt\src\db\db.py", line 120, in createSvc
    svc.save()
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 435, in save
    raise NotUniqueError(message % six.text_type(err))
mongoengine.errors.NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })

2020-04-27 22:35:31,338 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 22:35:31,341 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 22:35:31,343 | DEBUG | BDC7-L-9361NF2 |         [db createSvc] | Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 412, in save
    object_id = self._save_create(doc, force_insert, write_concern)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 477, in _save_create
    object_id = wc_collection.insert_one(doc).inserted_id
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 695, in insert_one
    self._insert(document,
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 610, in _insert
    return self._insert_one(
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 599, in _insert_one
    self.__database.client._retryable_write(
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\mongo_client.py", line 1491, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\mongo_client.py", line 1384, in _retry_with_session
    return func(session, sock_info, retryable)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 597, in _insert_command
    _check_write_command_response(result)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\helpers.py", line 221, in _check_write_command_response
    _raise_last_write_error(write_errors)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\helpers.py", line 202, in _raise_last_write_error
    raise DuplicateKeyError(error.get("errmsg"), 11000, error)
pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\Desktop\Devnetops\devnetops-feature_sprint1\UserMgmt\src\db\db.py", line 120, in createSvc
    svc.save()
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 435, in save
    raise NotUniqueError(message % six.text_type(err))
mongoengine.errors.NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })

2020-04-27 22:35:31,343 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 22:35:31,350 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 22:35:31,353 | DEBUG | BDC7-L-9361NF2 |         [db createRole] | Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 412, in save
    object_id = self._save_create(doc, force_insert, write_concern)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 477, in _save_create
    object_id = wc_collection.insert_one(doc).inserted_id
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 695, in insert_one
    self._insert(document,
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 610, in _insert
    return self._insert_one(
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 599, in _insert_one
    self.__database.client._retryable_write(
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\mongo_client.py", line 1491, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\mongo_client.py", line 1384, in _retry_with_session
    return func(session, sock_info, retryable)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 597, in _insert_command
    _check_write_command_response(result)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\helpers.py", line 221, in _check_write_command_response
    _raise_last_write_error(write_errors)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\helpers.py", line 202, in _raise_last_write_error
    raise DuplicateKeyError(error.get("errmsg"), 11000, error)
pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\Desktop\Devnetops\devnetops-feature_sprint1\UserMgmt\src\db\db.py", line 174, in createRole
    rol.save()
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 435, in save
    raise NotUniqueError(message % six.text_type(err))
mongoengine.errors.NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })

2020-04-27 22:35:31,353 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 22:35:31,638 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 22:35:31,640 | DEBUG | BDC7-L-9361NF2 |         [db createUser] | Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 412, in save
    object_id = self._save_create(doc, force_insert, write_concern)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 477, in _save_create
    object_id = wc_collection.insert_one(doc).inserted_id
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 695, in insert_one
    self._insert(document,
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 610, in _insert
    return self._insert_one(
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 599, in _insert_one
    self.__database.client._retryable_write(
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\mongo_client.py", line 1491, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\mongo_client.py", line 1384, in _retry_with_session
    return func(session, sock_info, retryable)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 597, in _insert_command
    _check_write_command_response(result)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\helpers.py", line 221, in _check_write_command_response
    _raise_last_write_error(write_errors)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\helpers.py", line 202, in _raise_last_write_error
    raise DuplicateKeyError(error.get("errmsg"), 11000, error)
pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\Desktop\Devnetops\devnetops-feature_sprint1\UserMgmt\src\db\db.py", line 45, in createUser
    usr.save()
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 435, in save
    raise NotUniqueError(message % six.text_type(err))
mongoengine.errors.NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })

2020-04-27 22:35:31,640 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 22:35:31,643 | ERROR | BDC7-L-9361NF2 |         [db authenticateUser] | Failed to verify user 'admin@acc.com'
2020-04-27 22:35:31,644 | DEBUG | BDC7-L-9361NF2 |         [db authenticateUser] | Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\Desktop\Devnetops\devnetops-feature_sprint1\UserMgmt\src\db\db.py", line 258, in authenticateUser
    return checkpw(passw, usr.password)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\bcrypt\__init__.py", line 100, in checkpw
    raise TypeError("Unicode-objects must be encoded before checking")
TypeError: Unicode-objects must be encoded before checking

2020-04-27 22:35:31,644 | ERROR | BDC7-L-9361NF2 |         [db authenticateUser] | Unicode-objects must be encoded before checking
2020-04-27 22:36:12,710 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 22:36:12,716 | DEBUG | BDC7-L-9361NF2 |         [db createSvc] | Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 412, in save
    object_id = self._save_create(doc, force_insert, write_concern)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 477, in _save_create
    object_id = wc_collection.insert_one(doc).inserted_id
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 695, in insert_one
    self._insert(document,
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 610, in _insert
    return self._insert_one(
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 599, in _insert_one
    self.__database.client._retryable_write(
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\mongo_client.py", line 1491, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\mongo_client.py", line 1384, in _retry_with_session
    return func(session, sock_info, retryable)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 597, in _insert_command
    _check_write_command_response(result)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\helpers.py", line 221, in _check_write_command_response
    _raise_last_write_error(write_errors)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\helpers.py", line 202, in _raise_last_write_error
    raise DuplicateKeyError(error.get("errmsg"), 11000, error)
pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\Desktop\Devnetops\devnetops-feature_sprint1\UserMgmt\src\db\db.py", line 120, in createSvc
    svc.save()
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 435, in save
    raise NotUniqueError(message % six.text_type(err))
mongoengine.errors.NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })

2020-04-27 22:36:12,716 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 22:36:12,718 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 22:36:12,719 | DEBUG | BDC7-L-9361NF2 |         [db createSvc] | Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 412, in save
    object_id = self._save_create(doc, force_insert, write_concern)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 477, in _save_create
    object_id = wc_collection.insert_one(doc).inserted_id
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 695, in insert_one
    self._insert(document,
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 610, in _insert
    return self._insert_one(
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 599, in _insert_one
    self.__database.client._retryable_write(
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\mongo_client.py", line 1491, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\mongo_client.py", line 1384, in _retry_with_session
    return func(session, sock_info, retryable)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 597, in _insert_command
    _check_write_command_response(result)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\helpers.py", line 221, in _check_write_command_response
    _raise_last_write_error(write_errors)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\helpers.py", line 202, in _raise_last_write_error
    raise DuplicateKeyError(error.get("errmsg"), 11000, error)
pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\Desktop\Devnetops\devnetops-feature_sprint1\UserMgmt\src\db\db.py", line 120, in createSvc
    svc.save()
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 435, in save
    raise NotUniqueError(message % six.text_type(err))
mongoengine.errors.NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })

2020-04-27 22:36:12,721 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 22:36:12,729 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 22:36:12,730 | DEBUG | BDC7-L-9361NF2 |         [db createRole] | Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 412, in save
    object_id = self._save_create(doc, force_insert, write_concern)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 477, in _save_create
    object_id = wc_collection.insert_one(doc).inserted_id
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 695, in insert_one
    self._insert(document,
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 610, in _insert
    return self._insert_one(
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 599, in _insert_one
    self.__database.client._retryable_write(
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\mongo_client.py", line 1491, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\mongo_client.py", line 1384, in _retry_with_session
    return func(session, sock_info, retryable)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 597, in _insert_command
    _check_write_command_response(result)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\helpers.py", line 221, in _check_write_command_response
    _raise_last_write_error(write_errors)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\helpers.py", line 202, in _raise_last_write_error
    raise DuplicateKeyError(error.get("errmsg"), 11000, error)
pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\Desktop\Devnetops\devnetops-feature_sprint1\UserMgmt\src\db\db.py", line 174, in createRole
    rol.save()
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 435, in save
    raise NotUniqueError(message % six.text_type(err))
mongoengine.errors.NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })

2020-04-27 22:36:12,731 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 22:36:12,995 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 22:36:12,997 | DEBUG | BDC7-L-9361NF2 |         [db createUser] | Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 412, in save
    object_id = self._save_create(doc, force_insert, write_concern)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 477, in _save_create
    object_id = wc_collection.insert_one(doc).inserted_id
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 695, in insert_one
    self._insert(document,
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 610, in _insert
    return self._insert_one(
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 599, in _insert_one
    self.__database.client._retryable_write(
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\mongo_client.py", line 1491, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\mongo_client.py", line 1384, in _retry_with_session
    return func(session, sock_info, retryable)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 597, in _insert_command
    _check_write_command_response(result)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\helpers.py", line 221, in _check_write_command_response
    _raise_last_write_error(write_errors)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\helpers.py", line 202, in _raise_last_write_error
    raise DuplicateKeyError(error.get("errmsg"), 11000, error)
pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\Desktop\Devnetops\devnetops-feature_sprint1\UserMgmt\src\db\db.py", line 45, in createUser
    usr.save()
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 435, in save
    raise NotUniqueError(message % six.text_type(err))
mongoengine.errors.NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })

2020-04-27 22:36:12,997 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 22:36:12,998 | ERROR | BDC7-L-9361NF2 |         [db authenticateUser] | Failed to verify user 'admin@acc.com'
2020-04-27 22:36:12,999 | DEBUG | BDC7-L-9361NF2 |         [db authenticateUser] | Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\Desktop\Devnetops\devnetops-feature_sprint1\UserMgmt\src\db\db.py", line 258, in authenticateUser
    return checkpw(passw, usr.password)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\bcrypt\__init__.py", line 100, in checkpw
    raise TypeError("Unicode-objects must be encoded before checking")
TypeError: Unicode-objects must be encoded before checking

2020-04-27 22:36:13,000 | ERROR | BDC7-L-9361NF2 |         [db authenticateUser] | Unicode-objects must be encoded before checking
2020-04-27 22:44:41,842 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 22:44:41,861 | DEBUG | BDC7-L-9361NF2 |         [db createSvc] | Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 412, in save
    object_id = self._save_create(doc, force_insert, write_concern)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 477, in _save_create
    object_id = wc_collection.insert_one(doc).inserted_id
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 695, in insert_one
    self._insert(document,
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 610, in _insert
    return self._insert_one(
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 599, in _insert_one
    self.__database.client._retryable_write(
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\mongo_client.py", line 1491, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\mongo_client.py", line 1384, in _retry_with_session
    return func(session, sock_info, retryable)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 597, in _insert_command
    _check_write_command_response(result)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\helpers.py", line 221, in _check_write_command_response
    _raise_last_write_error(write_errors)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\helpers.py", line 202, in _raise_last_write_error
    raise DuplicateKeyError(error.get("errmsg"), 11000, error)
pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\Desktop\Devnetops\devnetops-feature_sprint1\UserMgmt\src\db\db.py", line 120, in createSvc
    svc.save()
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 435, in save
    raise NotUniqueError(message % six.text_type(err))
mongoengine.errors.NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })

2020-04-27 22:44:41,861 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 22:44:41,864 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 22:44:41,866 | DEBUG | BDC7-L-9361NF2 |         [db createSvc] | Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 412, in save
    object_id = self._save_create(doc, force_insert, write_concern)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 477, in _save_create
    object_id = wc_collection.insert_one(doc).inserted_id
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 695, in insert_one
    self._insert(document,
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 610, in _insert
    return self._insert_one(
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 599, in _insert_one
    self.__database.client._retryable_write(
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\mongo_client.py", line 1491, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\mongo_client.py", line 1384, in _retry_with_session
    return func(session, sock_info, retryable)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 597, in _insert_command
    _check_write_command_response(result)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\helpers.py", line 221, in _check_write_command_response
    _raise_last_write_error(write_errors)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\helpers.py", line 202, in _raise_last_write_error
    raise DuplicateKeyError(error.get("errmsg"), 11000, error)
pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\Desktop\Devnetops\devnetops-feature_sprint1\UserMgmt\src\db\db.py", line 120, in createSvc
    svc.save()
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 435, in save
    raise NotUniqueError(message % six.text_type(err))
mongoengine.errors.NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })

2020-04-27 22:44:41,866 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 22:44:41,872 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 22:44:41,873 | DEBUG | BDC7-L-9361NF2 |         [db createRole] | Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 412, in save
    object_id = self._save_create(doc, force_insert, write_concern)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 477, in _save_create
    object_id = wc_collection.insert_one(doc).inserted_id
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 695, in insert_one
    self._insert(document,
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 610, in _insert
    return self._insert_one(
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 599, in _insert_one
    self.__database.client._retryable_write(
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\mongo_client.py", line 1491, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\mongo_client.py", line 1384, in _retry_with_session
    return func(session, sock_info, retryable)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 597, in _insert_command
    _check_write_command_response(result)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\helpers.py", line 221, in _check_write_command_response
    _raise_last_write_error(write_errors)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\helpers.py", line 202, in _raise_last_write_error
    raise DuplicateKeyError(error.get("errmsg"), 11000, error)
pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\Desktop\Devnetops\devnetops-feature_sprint1\UserMgmt\src\db\db.py", line 174, in createRole
    rol.save()
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 435, in save
    raise NotUniqueError(message % six.text_type(err))
mongoengine.errors.NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })

2020-04-27 22:44:41,874 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 22:44:42,138 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 22:44:42,140 | DEBUG | BDC7-L-9361NF2 |         [db createUser] | Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 412, in save
    object_id = self._save_create(doc, force_insert, write_concern)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 477, in _save_create
    object_id = wc_collection.insert_one(doc).inserted_id
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 695, in insert_one
    self._insert(document,
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 610, in _insert
    return self._insert_one(
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 599, in _insert_one
    self.__database.client._retryable_write(
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\mongo_client.py", line 1491, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\mongo_client.py", line 1384, in _retry_with_session
    return func(session, sock_info, retryable)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\collection.py", line 597, in _insert_command
    _check_write_command_response(result)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\helpers.py", line 221, in _check_write_command_response
    _raise_last_write_error(write_errors)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymongo\helpers.py", line 202, in _raise_last_write_error
    raise DuplicateKeyError(error.get("errmsg"), 11000, error)
pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\Desktop\Devnetops\devnetops-feature_sprint1\UserMgmt\src\db\db.py", line 45, in createUser
    usr.save()
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mongoengine\document.py", line 435, in save
    raise NotUniqueError(message % six.text_type(err))
mongoengine.errors.NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })

2020-04-27 22:44:42,140 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 22:44:42,142 | ERROR | BDC7-L-9361NF2 |         [db authenticateUser] | Failed to verify user 'admin@acc.com'
2020-04-27 22:44:42,143 | DEBUG | BDC7-L-9361NF2 |         [db authenticateUser] | Traceback (most recent call last):
  File "C:\Users\soumya.a.sen\Desktop\Devnetops\devnetops-feature_sprint1\UserMgmt\src\db\db.py", line 257, in authenticateUser
    return checkpw(passw.encode('utf8'), usr.password)
  File "C:\Users\soumya.a.sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\bcrypt\__init__.py", line 100, in checkpw
    raise TypeError("Unicode-objects must be encoded before checking")
TypeError: Unicode-objects must be encoded before checking

2020-04-27 22:44:42,143 | ERROR | BDC7-L-9361NF2 |         [db authenticateUser] | Unicode-objects must be encoded before checking
2020-04-27 22:45:45,993 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 22:45:46,002 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 22:45:46,006 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 22:45:46,009 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 22:45:46,017 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 22:45:46,020 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 22:45:46,321 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 22:45:46,322 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 22:45:46,324 | ERROR | BDC7-L-9361NF2 |         [db authenticateUser] | Failed to verify user 'admin@acc.com'
2020-04-27 22:45:46,325 | ERROR | BDC7-L-9361NF2 |         [db authenticateUser] | Unicode-objects must be encoded before checking
2020-04-27 22:56:00,808 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 22:56:00,822 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 22:56:00,826 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 22:56:00,828 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 22:56:00,835 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 22:56:00,837 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 22:56:01,112 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 22:56:01,114 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 22:56:01,373 | ERROR | BDC7-L-9361NF2 |         [db authenticateUser] | Failed to verify user 'admin@acc.com'
2020-04-27 22:56:01,375 | ERROR | BDC7-L-9361NF2 |         [db authenticateUser] | Unicode-objects must be encoded before checking
2020-04-27 22:56:59,299 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 22:56:59,304 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 22:56:59,306 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 22:56:59,308 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 22:56:59,315 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 22:56:59,316 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 22:56:59,580 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 22:56:59,582 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 22:57:39,104 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 22:57:39,110 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 22:57:39,112 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 22:57:39,114 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 22:57:39,126 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 22:57:39,128 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 22:57:39,388 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 22:57:39,389 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 22:57:39,392 | ERROR | BDC7-L-9361NF2 |         [db authenticateUser] | Failed to verify user 'admin@acc.com'
2020-04-27 22:57:39,393 | ERROR | BDC7-L-9361NF2 |         [db authenticateUser] | Unicode-objects must be encoded before checking
2020-04-27 22:57:56,727 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 22:57:56,748 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 22:57:56,750 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 22:57:56,752 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 22:57:56,757 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 22:57:56,760 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 22:57:57,056 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 22:57:57,058 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 23:00:05,019 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 23:00:05,027 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 23:00:05,032 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 23:00:05,034 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 23:00:05,040 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 23:00:05,042 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 23:00:05,305 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 23:00:05,307 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 23:00:14,634 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 23:00:14,636 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 23:02:23,626 | INFO | BDC7-L-9361NF2 |         [db createRole] | Role 'dev' has been created
2020-04-27 23:03:08,178 | INFO | BDC7-L-9361NF2 |         [db createUser] | User 'dev1@acc.com' created with roles 'dev'
2020-04-27 23:09:32,729 | ERROR | BDC7-L-9361NF2 |         [db addRoleToUser] | Unable to add new roles to the user 'dev1@acc.com'
2020-04-27 23:09:32,732 | ERROR | BDC7-L-9361NF2 |         [db addRoleToUser] | Not a query object: dev1@acc.com. Did you intend to use key=value?
2020-04-27 23:12:21,754 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 23:12:21,763 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 23:12:21,767 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 23:12:21,769 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 23:12:21,781 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 23:12:21,783 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 23:12:22,062 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 23:12:22,065 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 23:12:22,332 | ERROR | BDC7-L-9361NF2 |         [db addRoleToUser] | Unable to add new roles to the user 'dev1@acc.com'
2020-04-27 23:12:22,333 | ERROR | BDC7-L-9361NF2 |         [db addRoleToUser] | can only concatenate list (not "BaseQuerySet") to list
2020-04-27 23:17:25,465 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 23:17:25,480 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 23:17:25,482 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 23:17:25,484 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 23:17:25,494 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 23:17:25,497 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 23:17:25,782 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 23:17:25,805 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 23:17:26,071 | ERROR | BDC7-L-9361NF2 |         [db addRoleToUser] | Unable to add new roles to the user 'dev1@acc.com'
2020-04-27 23:17:26,072 | ERROR | BDC7-L-9361NF2 |         [db addRoleToUser] | can only concatenate list (not "BaseQuerySet") to list
2020-04-27 23:18:03,768 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 23:18:03,776 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 23:18:03,781 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 23:18:03,783 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 23:18:03,789 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 23:18:03,791 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 23:18:04,060 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 23:18:04,062 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 23:18:04,323 | INFO | BDC7-L-9361NF2 |         [db addRoleToUser] | New roles - admin added to the user 'dev1@acc.com'
2020-04-27 23:18:35,580 | ERROR | BDC7-L-9361NF2 |         [db removeRoleFrmUser] | Unable to remove roles from the user 'dev1@acc.com'
2020-04-27 23:18:35,582 | ERROR | BDC7-L-9361NF2 |         [db removeRoleFrmUser] | Not a query object: dev1@acc.com. Did you intend to use key=value?
2020-04-27 23:19:33,562 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 23:19:33,583 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 23:19:33,586 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 23:19:33,591 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 23:19:33,601 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 23:19:33,603 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 23:19:33,867 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 23:19:33,869 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 23:19:34,131 | INFO | BDC7-L-9361NF2 |         [db removeRoleFrmUser] | Roles - 'admin' has been removed from the user 'dev1@acc.com'
2020-04-27 23:20:08,316 | ERROR | BDC7-L-9361NF2 |         [db deleteUser] | Unable to remove roles from the user 'dev1@acc.com'
2020-04-27 23:20:08,318 | ERROR | BDC7-L-9361NF2 |         [db deleteUser] | Not a query object: dev1@acc.com. Did you intend to use key=value?
2020-04-27 23:21:23,927 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 23:21:23,933 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 23:21:23,935 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 23:21:23,937 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 23:21:23,943 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 23:21:23,946 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 23:21:24,208 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 23:21:24,209 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 23:21:24,480 | INFO | BDC7-L-9361NF2 |         [db deleteUser] | User 'dev1@acc.com' has been deleted
2020-04-27 23:23:28,118 | ERROR | BDC7-L-9361NF2 |         [db changePass] | Failed to change password for user 'dev1@acc.com'
2020-04-27 23:23:28,118 | ERROR | BDC7-L-9361NF2 |         [db changePass] | type object 'User' has no attribute 'object'
2020-04-27 23:25:05,361 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 23:25:05,370 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 23:25:05,373 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 23:25:05,376 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 23:25:05,383 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 23:25:05,385 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 23:25:05,652 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 23:25:05,654 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 23:25:05,910 | ERROR | BDC7-L-9361NF2 |         [db changePass] | Failed to change password for user 'dev1@acc.com'
2020-04-27 23:25:05,910 | ERROR | BDC7-L-9361NF2 |         [db changePass] | 'NoneType' object has no attribute 'update'
2020-04-27 23:25:33,945 | INFO | BDC7-L-9361NF2 |         [db createUser] | User 'dev1@acc.com' created with roles 'dev'
2020-04-27 23:25:38,754 | ERROR | BDC7-L-9361NF2 |         [db changePass] | Failed to change password for user 'dev1@acc.com'
2020-04-27 23:25:38,761 | ERROR | BDC7-L-9361NF2 |         [db changePass] | StringField only accepts string values
2020-04-27 23:29:04,685 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 23:29:04,692 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 23:29:04,696 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 23:29:04,699 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 23:29:04,706 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 23:29:04,709 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 23:29:04,978 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 23:29:04,979 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 23:29:05,489 | ERROR | BDC7-L-9361NF2 |         [db changePass] | Failed to change password for user 'dev1@acc.com'
2020-04-27 23:29:05,494 | ERROR | BDC7-L-9361NF2 |         [db changePass] | StringField only accepts string values
2020-04-27 23:29:47,305 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 23:29:47,314 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 23:29:47,316 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 23:29:47,318 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 23:29:47,326 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 23:29:47,329 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 23:29:47,611 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 23:29:47,613 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 23:29:48,402 | ERROR | BDC7-L-9361NF2 |         [db changePass] | Failed to change password for user 'dev1@acc.com'
2020-04-27 23:29:48,407 | ERROR | BDC7-L-9361NF2 |         [db changePass] | StringField only accepts string values
2020-04-27 23:30:33,748 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 23:30:33,753 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 23:30:33,756 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 23:30:33,760 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 23:30:33,768 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 23:30:33,770 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 23:30:34,038 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 23:30:34,040 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 23:30:34,800 | ERROR | BDC7-L-9361NF2 |         [db changePass] | Failed to change password for user 'dev1@acc.com'
2020-04-27 23:30:34,804 | ERROR | BDC7-L-9361NF2 |         [db changePass] | StringField only accepts string values
2020-04-27 23:31:04,276 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 23:31:04,287 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 23:31:04,290 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 23:31:04,292 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 23:31:04,304 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 23:31:04,306 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 23:31:04,577 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 23:31:04,579 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 23:31:05,091 | INFO | BDC7-L-9361NF2 |         [db changePass] | Password successfully changed for user 'dev1@acc.com'
2020-04-27 23:37:52,128 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 23:37:52,152 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 23:37:52,154 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 23:37:52,156 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 23:37:52,162 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 23:37:52,164 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 23:37:52,435 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 23:37:52,437 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 23:38:44,775 | INFO | BDC7-L-9361NF2 |         [db createSvc] | Service 'svc3' has been created
2020-04-27 23:40:09,947 | INFO | BDC7-L-9361NF2 |         [db createRole] | Role 'test' has been created
2020-04-27 23:40:52,693 | ERROR | BDC7-L-9361NF2 |         [db addSvcToRole] | Failed to add services to role 'test'
2020-04-27 23:40:52,694 | ERROR | BDC7-L-9361NF2 |         [db addSvcToRole] | 'BaseQuerySet' object has no attribute 'read'
2020-04-27 23:44:23,576 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 23:44:23,584 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 23:44:23,587 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 23:44:23,590 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 23:44:23,598 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 23:44:23,600 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 23:44:23,870 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 23:44:23,872 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 23:45:16,127 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 23:45:16,133 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 23:45:16,135 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 23:45:16,137 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 23:45:16,148 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 23:45:16,149 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 23:45:16,416 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 23:45:16,419 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 23:45:45,432 | ERROR | BDC7-L-9361NF2 |         [db addSvcToRole] | Failed to add services to role 'test'
2020-04-27 23:45:45,433 | ERROR | BDC7-L-9361NF2 |         [db addSvcToRole] | can only concatenate list (not "BaseQuerySet") to list
2020-04-27 23:46:18,167 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 23:46:18,188 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 23:46:18,191 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 23:46:18,193 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 23:46:18,200 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 23:46:18,202 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 23:46:18,472 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 23:46:18,474 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 23:46:18,732 | ERROR | BDC7-L-9361NF2 |         [db addSvcToRole] | Failed to add services to role 'test'
2020-04-27 23:46:18,732 | ERROR | BDC7-L-9361NF2 |         [db addSvcToRole] | can only concatenate list (not "BaseQuerySet") to list
2020-04-27 23:47:44,200 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 23:47:44,207 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 23:47:44,209 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 23:47:44,211 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 23:47:44,222 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 23:47:44,245 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 23:47:44,517 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 23:47:44,518 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 23:47:44,780 | ERROR | BDC7-L-9361NF2 |         [db addSvcToRole] | Failed to add services to role 'test'
2020-04-27 23:47:44,780 | ERROR | BDC7-L-9361NF2 |         [db addSvcToRole] | can only concatenate list (not "BaseQuerySet") to list
2020-04-27 23:52:28,156 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 23:52:28,164 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 23:52:28,166 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 23:52:28,168 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 23:52:28,174 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 23:52:28,176 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 23:52:28,439 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 23:52:28,440 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 23:52:28,706 | INFO | BDC7-L-9361NF2 |         [db addSvcToRole] | Services added to role 'test'
2020-04-27 23:52:40,104 | ERROR | BDC7-L-9361NF2 |         [db remSvcFrmRole] | Failed to remove services from role 'test'
2020-04-27 23:52:40,104 | ERROR | BDC7-L-9361NF2 |         [db remSvcFrmRole] | 'BaseQuerySet' object has no attribute 'read'
2020-04-27 23:53:20,155 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 23:53:20,161 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 23:53:20,164 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 23:53:20,166 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 23:53:20,176 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 23:53:20,179 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 23:53:20,456 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 23:53:20,458 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 23:53:20,727 | ERROR | BDC7-L-9361NF2 |         [db remSvcFrmRole] | Failed to remove services from role 'test'
2020-04-27 23:53:20,728 | ERROR | BDC7-L-9361NF2 |         [db remSvcFrmRole] | unsupported operand type(s) for -: 'set' and 'BaseQuerySet'
2020-04-27 23:53:53,699 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-27 23:53:53,707 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-27 23:53:53,709 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-27 23:53:53,711 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-27 23:53:53,721 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-27 23:53:53,723 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-27 23:53:53,986 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-27 23:53:53,988 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-27 23:53:54,253 | INFO | BDC7-L-9361NF2 |         [db remSvcFrmRole] | Services removed from role 'test'
2020-04-27 23:54:04,191 | INFO | BDC7-L-9361NF2 |         [db remSvcFrmRole] | Services removed from role 'test'
2020-04-27 23:55:03,202 | INFO | BDC7-L-9361NF2 |         [db createRole] | Role 'test' has been created
2020-04-27 23:56:01,778 | INFO | BDC7-L-9361NF2 |         [db deleteRole] | Role 'test' deleted successfully
2020-04-28 00:03:36,442 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-28 00:03:36,450 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-28 00:03:36,452 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-28 00:03:36,454 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-28 00:03:36,465 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-28 00:03:36,467 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-28 00:03:36,732 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-28 00:03:36,734 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-28 00:03:44,584 | INFO | BDC7-L-9361NF2 |         [db createRole] | Role 'test' has been created
2020-04-28 00:03:54,356 | INFO | BDC7-L-9361NF2 |         [db remSvcFrmRole] | Services removed from role 'test'
2020-04-28 10:21:03,969 | INFO | BDC7-L-9361NF2 |         [db createSvc] | Service 'svc1' has been created
2020-04-28 10:21:03,973 | INFO | BDC7-L-9361NF2 |         [db createSvc] | Service 'svc2' has been created
2020-04-28 10:21:04,035 | INFO | BDC7-L-9361NF2 |         [db createRole] | Role 'admin' has been created
2020-04-28 10:21:04,590 | INFO | BDC7-L-9361NF2 |         [db createUser] | User 'admin@acc.com' created with roles 'admin'
2020-04-28 10:21:58,806 | INFO | BDC7-L-9361NF2 |         [db createSvc] | Service 'svc1' has been created
2020-04-28 10:21:58,809 | INFO | BDC7-L-9361NF2 |         [db createSvc] | Service 'svc2' has been created
2020-04-28 10:21:58,873 | INFO | BDC7-L-9361NF2 |         [db createRole] | Role 'admin' has been created
2020-04-28 10:21:59,231 | INFO | BDC7-L-9361NF2 |         [db createUser] | User 'admin@acc.com' created with roles 'admin'
2020-04-28 10:35:56,106 | ERROR | BDC7-L-9361NF2 |         [db addSvcToRole] | Failed to add services to role 'admin'
2020-04-28 10:35:56,109 | ERROR | BDC7-L-9361NF2 |         [db addSvcToRole] | 'NoneType' object has no attribute 'update'
2020-04-28 10:35:56,109 | INFO | BDC7-L-9361NF2 |         [db createSvc] | Service 'svc1' has been created
2020-04-28 10:35:56,123 | ERROR | BDC7-L-9361NF2 |         [db addSvcToRole] | Failed to add services to role 'admin'
2020-04-28 10:35:56,123 | ERROR | BDC7-L-9361NF2 |         [db addSvcToRole] | 'NoneType' object has no attribute 'update'
2020-04-28 10:35:56,125 | INFO | BDC7-L-9361NF2 |         [db createSvc] | Service 'svc2' has been created
2020-04-28 10:35:56,137 | INFO | BDC7-L-9361NF2 |         [db createRole] | Role 'admin' has been created
2020-04-28 10:35:56,838 | INFO | BDC7-L-9361NF2 |         [db createUser] | User 'admin@acc.com' created with roles 'admin'
2020-04-28 10:38:21,879 | INFO | BDC7-L-9361NF2 |         [db addSvcToRole] | Services added to role 'admin'
2020-04-28 10:38:21,879 | INFO | BDC7-L-9361NF2 |         [db createSvc] | Service 'svc3' has been created
2020-04-28 10:38:29,170 | INFO | BDC7-L-9361NF2 |         [db createRole] | Role 'dev' has been created
2020-04-28 10:40:08,809 | INFO | BDC7-L-9361NF2 |         [db createUser] | User 'dev1@acc.com' created with roles 'dev'
2020-04-28 10:42:41,084 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-28 10:42:41,123 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-28 10:42:41,126 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-28 10:42:41,129 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-28 10:42:41,143 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-28 10:42:41,147 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-28 10:42:41,515 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-28 10:42:41,517 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-28 10:44:34,682 | INFO | BDC7-L-9361NF2 |         [db changePass] | Password successfully changed for user 'dev1@acc.com'
2020-04-28 10:45:45,225 | INFO | BDC7-L-9361NF2 |         [db addRoleToUser] | New roles - admin added to the user 'dev1@acc.com'
2020-04-28 10:46:41,101 | INFO | BDC7-L-9361NF2 |         [db removeRoleFrmUser] | Roles - 'admin' has been removed from the user 'dev1@acc.com'
2020-04-28 10:48:16,378 | INFO | BDC7-L-9361NF2 |         [db deleteUser] | User 'dev1@acc.com' has been deleted
2020-04-28 10:50:01,758 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-28 10:50:01,771 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-28 10:50:01,776 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-28 10:50:01,778 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-28 10:50:01,790 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-28 10:50:01,793 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-28 10:50:02,207 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-28 10:50:02,228 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
2020-04-28 10:50:02,569 | ERROR | BDC7-L-9361NF2 |         [db addSvcToRole] | Failed to add services to role 'test'
2020-04-28 10:50:02,570 | ERROR | BDC7-L-9361NF2 |         [db addSvcToRole] | 'NoneType' object has no attribute 'update'
2020-04-28 10:50:22,111 | INFO | BDC7-L-9361NF2 |         [db addSvcToRole] | Services added to role 'dev'
2020-04-28 10:50:46,403 | INFO | BDC7-L-9361NF2 |         [db remSvcFrmRole] | Services removed from role 'dev'
2020-04-28 10:51:05,414 | INFO | BDC7-L-9361NF2 |         [db deleteRole] | Role 'dev' deleted successfully
2020-04-28 11:02:28,226 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc1
2020-04-28 11:02:28,239 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc1" })
2020-04-28 11:02:28,242 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Failed to create service svc2
2020-04-28 11:02:28,245 | ERROR | BDC7-L-9361NF2 |         [db createSvc] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.services index: name_1 dup key: { name: "svc2" })
2020-04-28 11:02:28,254 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Failed to create role 'admin'
2020-04-28 11:02:28,257 | ERROR | BDC7-L-9361NF2 |         [db createRole] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.role index: name_1 dup key: { name: "admin" })
2020-04-28 11:02:28,804 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Failed to create user 'admin@acc.com'
2020-04-28 11:02:28,810 | ERROR | BDC7-L-9361NF2 |         [db createUser] | Tried to save duplicate unique keys (E11000 duplicate key error collection: testnetops.user index: email_1 dup key: { email: "admin@acc.com" })
